scss_files:
  - 'scss/**/*.scss'

linters:
  BorderZero:
    enabled: true
    convention: none
  Comment:
    enabled: true
    exclude:
      - scss/main.scss
  ChainedClasses:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    enabled: true
    character: tab
    width: 1
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: true
    order: concentric
  PropertyUnits:
    enabled: true
    global: ['rem', 'px', '%']
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: true
    exclude:
      - scss/layout/_debug.scss
      - scss/layout/_sidebar.scss
  TrailingZero:
    enabled: true
  UrlFormat:
    enabled: true
    exclude:
      - scss/layout/_header.scss
  UrlQuotes:
    enabled: true
    exclude:
      - scss/layout/_header.scss
